server:
  port: 8899
#logging:
#  level:
#    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/locals_old?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      # 生产时ddl-auto应改为none
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
# JWT
jwt:
  header: Authorization
  secret: 6a63a7bf474249167a2010f4dd8ffa91c7cfdb4322e43555f243df2ab42edb959c98a862d88dd6ac8e031acb11cfc2f3800c03a802bd405e0614331545e8e3fb
  expiration: 3600
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
wechat:
  appid: wxb902b447879279ab
  secret: